_BASE_: "Base-ICDAR2013.yaml"
MODEL:
  WEIGHTS: "https://dl.fbaipublicfiles.com/detectron/ImageNetPretrained/MSRA/R-50.pkl"
  BACKBONE:
    NAME: "build_fcos_resnet_bifpn_backbone"
  BiFPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    OUT_CHANNELS: 256
    NUM_REPEATS: 2
    NORM: "SyncBN"
  RESNETS:
    DEPTH: 50
  BATEXT:
    RECOGNIZER: "attn"
    USE_COORDCONV: True
    USE_AET: True
  FCOS:
    # Best e2e: 0.5; Best det: 0.4
    INFERENCE_TH_TEST: 0.5
SOLVER:
  IMS_PER_BATCH: 1
  BASE_LR: 0.0001
  STEPS: (80000, 120000)
  MAX_ITER: 160000
  CHECKPOINT_PERIOD: 20000
TEST:
  EVAL_PERIOD: 20000
OUTPUT_DIR: "/gdrive/MyDrive/video-text-spotting/ABCNetV2/evaluation/icdar2013-finetuning/v2_attn_R_50"
